Repository TLE-MEC/Hack-CP-DSA, pull requests merged in 2021-10, with the labels that each got.

#83 Minimum Time to Type Word Using Special Typewriter
  Leetcode/Minimum Time to Type Word Using Special Typewriter/readme.md
  Leetcode/Minimum Time to Type Word Using Special Typewriter/solution.cpp
Labels: changes-needed

#67 Added Hacker Rank Problems
  Hackerrank/Apple and Orange/Apple and Orange.py
  Hackerrank/Apple and Orange/README.md
  Hackerrank/Grading Students/Grading Students.py
  Hackerrank/Grading Students/README.md
  Hackerrank/Number Line Jumps/Number Line Jumps.py
  Hackerrank/Number Line Jumps/README.md
Labels: changes-needed

#71 added Hackerrank Sherlock and Anagram Solution
  Hackerrank/SherlockAnagram/readme.md
  Hackerrank/SherlockAnagram/solution.cpp
Labels: changes-needed

#44 Added leetcode problem in cpp
  Leetcode/Letter Combination of Phone number/Readme.md
  Leetcode/Letter Combination of Phone number/soluion.cpp
Labels: changes-needed

#88 Added first unique character in string using python
  Leetcode/First unique character in sting/readme.md
  Leetcode/First unique character in sting/solution.py
Labels: changes-needed

#121 Remove Duplicates from Sorted Array
  Leetcode/Remove Duplicates from Sorted Array/Readme.md
  Leetcode/Remove Duplicates from Sorted Array/solution.py
Labels: changes-needed, hacktoberfest-accepted

#157 Added Leetcode Count Inversions
  Leetcode/Count Inversions/readme.md
  Leetcode/Count Inversions/solution.cpp
Labels: hacktoberfest-accepted

#191 DayOfProgrammer Solution in C
  Hackerrank/Day of the programmer/DayOfProgrammer.c
Labels: hacktoberfest-accepted

#195 [Added] Maximum product subarray problem
  Leetcode/Maximum Product Subarray/readme.md
  Leetcode/Maximum Product Subarray/solution.cpp
Labels: hacktoberfest-accepted

#93 Valid Anagram in Java
  Codeforces/Multiply by two divide by six/ README.md
  Codeforces/Multiply by two divide by six/solution.py
  Leetcode/Valid Anagram/README.md
  Leetcode/Valid Anagram/solution.java
Labels: hacktoberfest-accepted

#97 subtract-the-product-and-sum-of-digits-of-an-integer
  Leetcode/Subtract the Product and Sum of Digits of an Integer/readme.md
  Leetcode/Subtract the Product and Sum of Digits of an Integer/solution.java
Labels: hacktoberfest-accepted

#148 Added Increasing Triplet Subsequence(Leetcode)
  Leetcode/Increasing Triplet Subsequence/readme.md
  Leetcode/Increasing Triplet Subsequence/solution.cpp
  Leetcode/Multiply Strings/readme.md
  Leetcode/Multiply Strings/solution.cpp
Labels: hacktoberfest-accepted

#165 Added Coding Ninjas
  CP-DSA_RESOURCES.md
Labels: hacktoberfest-accepted

#188 Added Leetcode Reshape the Matrix
  Leetcode/Reshape the Matrix/readme.md
  Leetcode/Reshape the Matrix/solution.cpp
Labels: hacktoberfest-accepted

#190 Leetcode - Linked List Cycle
  Leetcode/Linked List Cycle/readme.md
  Leetcode/Linked List Cycle/solution.cpp
Labels: hacktoberfest-accepted

#199 Added Hackerrank CamelCase
  Hackerrank/CamelCase/readme.md
  Hackerrank/CamelCase/solution.cpp
Labels: hacktoberfest-accepted

#202 adding solution for "Plus One" (Leetcode)
  Leetcode/Plus One/readme.md
  Leetcode/Plus One/solution.py
Labels: hacktoberfest-accepted

#167 Longest consecutive sequence (Problem 128) (UNION FIND)
  Leetcode/Longest Consecutive Sequence/README.md
  Leetcode/Longest Consecutive Sequence/solution.cpp
Labels: hacktoberfest-accepted

#208 added <Codeforces> <Mocha and Hiking>
  Codeforces/Mocha and Hiking/README.md
  Codeforces/Mocha and Hiking/mocha_and_hiking.cpp
Labels: hacktoberfest-accepted

#196 added Codechef Maximum Array Xor
  Codechef/Maximum Array Xor/readme.md
  Codechef/Maximum Array Xor/solution.cpp
Labels: hacktoberfest-accepted

#177 added Leetcode Maximum Depth of Binary Tree
  Leetcode/Maximum Depth of Binary Tree/readme.md
  Leetcode/Maximum Depth of Binary Tree/solution.cpp
  Leetcode/Single Number/readme.md
  Leetcode/Single Number/solution.cpp
Labels: hacktoberfest-accepted

#185 QAQ codeforces
  Codeforces/QAQ/readme.md
  Codeforces/QAQ/solution.cpp
Labels: hacktoberfest-accepted

#189 Added Diameter of graph cpp solution to Codeforces folder
  Codeforces/Diameter of Graph/readme.md
  Codeforces/Diameter of Graph/solution.cpp
  Hackerrank/Day of the programmer/solution2.cpp
Labels: hacktoberfest-accepted

#193 Adding Kth smallest element in a sorted matrix (Leetcode) Solution
  Leetcode/Kth Smallest Element in a sorted Matrix/readme.md
  Leetcode/Kth Smallest Element in a sorted Matrix/solution.cpp
Labels: hacktoberfest-accepted

#201 removed palindrome and added reverse linked list
  Hackerrank/Reverse Linked List/readme.md
  Hackerrank/Reverse Linked List/solution.py
Labels: hacktoberfest-accepted

#205 Added search in a 2d matrix
  Leetcode/Search a 2D matrix/readme.md
  Leetcode/Search a 2D matrix/solution.cpp
Labels: hacktoberfest-accepted

#209 added Hackerrank Sherlock and Squares
  Hackerrank/Drawing Book/readme.md
  Hackerrank/Sherl/readme.md
  Hackerrank/Sherl/solution.cpp
Labels: hacktoberfest-accepted

#210 Day of the Programmer (Python)
  Hackerrank/Day of the programmer/solution3.py
Labels: hacktoberfest-accepted

#218 Added Word Search
  Leetcode/Word Search/readme.md
  Leetcode/Word Search/solution.cpp
Labels: hacktoberfest-accepted

#222 MEC added leetcode Min Cost Climbing Stairs
  Leetcode/Min Cost Climbing Stairs/readme.md
  Leetcode/Min Cost Climbing Stairs/solution.cpp
Labels: hacktoberfest-accepted

#207 Added a book - Introduction to Algorithms (CLRS)
  CP-DSA_RESOURCES.md
Labels: hacktoberfest-accepted

#211 added Leetcode Product of Array Except Self
  Leetcode/Product of Array Except Self/Solution.java
  Leetcode/Product of Array Except Self/readme.md
Labels: hacktoberfest-accepted

#215 Added Leetcode 2 problems
  CP-DSA_RESOURCES.md
  Leetcode/Maximize Distance to Closest Person/README.md
  Leetcode/Maximize Distance to Closest Person/solution.cpp
  Leetcode/Number Of Longest Increasing Subsequence/README.md
  Leetcode/Number Of Longest Increasing Subsequence/solution.cpp
Labels: hacktoberfest-accepted

#216 Adding Solution For Hackerrank Problem Electronics Shop
  Hackerrank/Electronics Shop/README.md
  Hackerrank/Electronics Shop/solution.py
Labels: hacktoberfest-accepted

#217 Added Problem: Leetcode/Median in a stream of integers
  Leetcode/Find Median from Data Stream/README.md
  Leetcode/Find Median from Data Stream/Solution.cpp
Labels: hacktoberfest-accepted

#219 Added a new problem and solution from codechef
  Codechef/Chef and Easy Queries/Readme.md
  Codechef/Chef and Easy Queries/Solution.py
Labels: hacktoberfest-accepted

#223 Adding Solution For hackerearth Problem Likeable arrays in C++
  Hackerearth/Likeable arrays/readme.md
  Hackerearth/Likeable arrays/solution.cpp
Labels: hacktoberfest-accepted

#224 Codeforces Problem
  Codeforces/Young Photographer/readme.md
  Codeforces/Young Photographer/solution.cpp
Labels: hacktoberfest-accepted

#227 added Codechef ATM
  Codechef/ATM/readme.md
  Codechef/ATM/solution.cpp
Labels: hacktoberfest-accepted

#225 Added Palindromic Substrings
  Leetcode/Palindromic Substrings/readme.md
  Leetcode/Palindromic Substrings/solution.cpp
Labels: hacktoberfest-accepted

#203 Added Larry's Array Problem
  Hackerearth/Alice and candies/readme.md
  Hackerearth/Alice and candies/solution.cpp
  Hackerrank/Larry's Array/readme.md
  Hackerrank/Larry's Array/solution.cpp
Labels: hacktoberfest-accepted

#231 Added Doctor Chef Problem
  Codechef/Doctor Chef (DRCHEF)/readme.md
  Codechef/Doctor Chef (DRCHEF)/solution.cpp
Labels: hacktoberfest-accepted

#235 Permutation Sequence Leetcode
  Leetcode/Permutation Sequence/readme.md
  Leetcode/Permutation Sequence/solution.cpp
Labels: hacktoberfest-accepted

#239 Shambhavi - Array intersection problem added
  GeeksForGeeks/Intersection of arrays/README.md
  GeeksForGeeks/Intersection of arrays/Solution.cpp
Labels: hacktoberfest-accepted

#238 Add Codeforces Problem
  Codeforces/Regular Bracket Sequences/readme.md
  Codeforces/Regular Bracket Sequences/solution.cpp
Labels: hacktoberfest-accepted

#194 Day of a programmer
  Codeforces/A-Puzzles/readme.md
  Codeforces/A-Puzzles/solution.cpp
  Hackerrank/Day of a Programmer/readme.md
  Hackerrank/Day of a Programmer/solution.cpp
Labels: hacktoberfest-accepted

#246 Added CodeChef Problem and Solution
  Codechef/Reverse a Number/readme.md
  Codechef/Reverse a Number/solution.py
Labels: hacktoberfest-accepted

#242 added solution for remone problem on codechef
  Codechef/Remove One Element/readme.md
  Codechef/Remove One Element/solution.cpp
Labels: hacktoberfest-accepted

#254 Added new CodeChef Solution: Maximum Weight Difference
  Codechef/Maximum Weight Difference/readme.md
  Codechef/Maximum Weight Difference/solution.java
Labels: hacktoberfest-accepted

#232 added Leetcode Find K Closest Elements
  Leetcode/Find K Closest Elements/Solution.java
  Leetcode/Find K Closest Elements/readme.md
  Leetcode/Find Peak Element/Solution.java
  Leetcode/Find Peak Element/readme.md
Labels: hacktoberfest-accepted

#236 added Threeboxes Codechef
  Codechef/three boxes/readme.md
  Codechef/three boxes/threeboxes.cpp
Labels: hacktoberfest-accepted

#181 Added rotate array problem to leetcode section
  Leetcode/Rotate array to right/readme.md
  Leetcode/Rotate array to right/solution.cpp
Labels: hacktoberfest-accepted

#240 Leetcode "Shuffle the Array" (Easy)
  Leetcode/Shuffle the Array/Solution.java
  Leetcode/Shuffle the Array/readme.md
Labels: hacktoberfest-accepted

#256 Solved : Mini-Max Sum | HackerRank
  Hackerrank/Mini-Max Sum/readme.md
  Hackerrank/Mini-Max Sum/solution.py
Labels: hacktoberfest-accepted

#260 Solution and link added for New Companies SQL
  Hackerrank/New Companies/Readme.md
  Hackerrank/New Companies/Solution.sql
Labels: hacktoberfest-accepted

#263 Codeforces Problem D
  Codeforces/AND  OR and square sum/solution.cpp
  Codeforces/AND OR and square sum/readme.md
Labels: hacktoberfest-accepted

#267 Added total expenses in c++
  Codechef/Total Expenses/readme.md
  Codechef/Total Expenses/solution.cpp
Labels: hacktoberfest-accepted

#249 Find The Array
  Codeforces/Find The Array/README.md
  Codeforces/Find The Array/solution.java
Labels: hacktoberfest-accepted

#22 Codechef September Lunchtime question
  Codechef/Interesting Representation/Readme.md
  Codechef/Interesting Representation/solution.cpp
Labels: hacktoberfest-accepted

#77 Solution for leetcode problem Reverse a linkedlist
  Leetcode/Reverse Linkedlist/readme.md
  Leetcode/Reverse Linkedlist/solution.cpp
Labels: hacktoberfest-accepted

#192 count sorted vowel strings
  Leetcode/Count Sorted Vowel Strings/readme.md
  Leetcode/Count Sorted Vowel Strings/solution.cpp
Labels: hacktoberfest-accepted

#280 Preorder to Postorder GFG solution added
  GeeksForGeeks/Preorder to Postorder/README.md
  GeeksForGeeks/Preorder to Postorder/Solution.java
Labels: hacktoberfest-accepted

#279 Add Young Physicist_CodeForces
  Codeforces/Queue at the School/readme.md
  Codeforces/Queue at the School/solution.cpp
  Codeforces/Young Physicist/readme.md
  Codeforces/Young Physicist/solution.cpp
Labels: hacktoberfest-accepted

#277 Added Hackerland Radio Transmitters in Hackerrank
  Hackerrank/Hackerland Radio Transmitters/readme.md
  Hackerrank/Hackerland Radio Transmitters/solution.cpp
Labels: hacktoberfest-accepted

#273 added Leetcode Rotting Oranges
  Leetcode/Rotting Oranges/readme.md
  Leetcode/Rotting Oranges/solution.cpp
Labels: hacktoberfest-accepted

#269 Binary Search!!
  Leetcode/BinarySearch/Readme.md
  Leetcode/BinarySearch/solution.py
Labels: hacktoberfest-accepted

#265 Added Last stone weight solution in C++
  Leetcode/Last Stone Weight/readme.md
  Leetcode/Last Stone Weight/solution.cpp
  Leetcode/MaximumSubarray/README.md
  Leetcode/MaximumSubarray/solution.java
Labels: hacktoberfest-accepted

#261 added solution for the problem bigger is greater of hackerrank
  Hackerrank/Bigger is Greater/readme.md
  Hackerrank/Bigger is Greater/solution.cpp
Labels: hacktoberfest-accepted

#257 added edit distance concept in leetcode folder
  Leetcode/Edit Distance/readme.md
  Leetcode/Edit Distance/solution.cpp
Labels: hacktoberfest-accepted

#251 Harsh
  Leetcode/K-Concatenation Maximum Sum/readme.md
  Leetcode/K-Concatenation Maximum Sum/solution.cpp
Labels: hacktoberfest-accepted

#282 Added Distinct Subsequences problem leetcode
  Hackerrank/Drawing Book/readme.md
  Leetcode/Distinct subsequences/readme.md
  Leetcode/Distinct subsequences/solution.py
  Leetcode/First Missing Positive/README.md
  Leetcode/First Missing Positive/solution.py
  Leetcode/Median of Two Sorted Arrays/README.md
  Leetcode/TaskScheduler/README.md
  Leetcode/TaskScheduler/solution.py
  URIOnlineJudge/Triangle/Readme.md
  URIOnlineJudge/Triangle/solution.py
Labels: hacktoberfest-accepted

#271 added Leetcode jump-game-ii
  Leetcode/Jump Game 2/README.md
  Leetcode/Jump Game 2/solution.cpp
Labels: hacktoberfest-accepted

#274 added codeforces Almost All Divisors
  Codeforces/Almost All Divisors/readme.md
  Codeforces/Almost All Divisors/solution.cpp
Labels: hacktoberfest-accepted

#284 Borze_Codeforces
  Borze/readme.md
  Borze/solution.cpp
Labels: hacktoberfest-accepted

#243 Leetcode additions
  Leetcode/Group the People Given the Group Size They Belong To/Readme.md
  Leetcode/Group the People Given the Group Size They Belong To/solution.py
  Leetcode/Max Increase to Keep City Skyline/Readme.md
  Leetcode/Max Increase to Keep City Skyline/solution.py
  Leetcode/Sort the Matrix Diagonally/Readme.md
  Leetcode/Sort the Matrix Diagonally/solution.py
Labels: hacktoberfest-accepted

#286 Added Median of 2 Sorted Arrays of Different Sizes GFG
  GeeksForGeeks/Median of 2 Sorted Arrays of Different Sizes/readme.md
  GeeksForGeeks/Median of 2 Sorted Arrays of Different Sizes/solution.java
Labels: hacktoberfest-accepted

#244 Added Leetcode XOR Queries of a Subarray
  Leetcode/Remove Nth Node From End of List/readme.md
  Leetcode/Remove Nth Node From End of List/solution.cpp
Labels: hacktoberfest-accepted

#259 Max Points on a Line Leetcode
  Leetcode/Max Points on a Line/readme.md
  Leetcode/Max Points on a Line/solution.cpp
Labels: hacktoberfest-accepted

#290 Added Leetcode-Course Schedule Problem
  Leetcode/Course Schedule/readme.md
  Leetcode/Course Schedule/solution.cpp
  PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted

#285 Solution to Sign of the Product of an Array
  Leetcode/Sign of the Product of an Array/Readme.md
  Leetcode/Sign of the Product of an Array/Solution.cpp
Labels: hacktoberfest-accepted

#287 Climbing the leaderboard
  Hackerrank/Climbing the Leaderboard/readme.md
  Hackerrank/Climbing the Leaderboard/solution.cpp
Labels: hacktoberfest-accepted

#294 add easy cpp solution of plusone.
  Leetcode/Plus One/solution2.cpp
Labels: hacktoberfest-accepted

#299 Minimum Window Substring Leetcode
  Leetcode/Minimum Window Substring/readme.md
  Leetcode/Minimum Window Substring/solution.cpp
Labels: hacktoberfest-accepted

#303 Combination Sum Leetcode
  Leetcode/Combination Sum/readme.md
  Leetcode/Combination Sum/solution.cpp
Labels: hacktoberfest-accepted

#306 Caesar Cipher Program from Hackerrank
  Hackerrank/Caesar Cipher/readme.md
  Hackerrank/Caesar Cipher/solution.cpp
Labels: hacktoberfest-accepted

#308 Added Leetcode Arithmetic Subarrays
  Leetcode/All Possible Binary Trees/readme.md
  Leetcode/All Possible Binary Trees/solution.cpp
  Leetcode/Arithmetic Subarrays/readme.md
  Leetcode/Arithmetic Subarrays/solution.cpp
Labels: hacktoberfest-accepted

#300 max chunks to make sorted
  Leetcode/Max Chunks To Make Sorted/README.md
  Leetcode/Max Chunks To Make Sorted/Solution.cpp
Labels: hacktoberfest-accepted

#311 Added Leetcode/Triangle
  Leetcode/Triangle/readme.md
  Leetcode/Triangle/solution.cpp
Labels: hacktoberfest-accepted

#307 added Hackerrank billdivisiom
  Hackerrank/Bill Division/Solution.java
  Hackerrank/Bill Division/readme.md
Labels: hacktoberfest-accepted

#295 Added a tutorial
  CP-DSA_RESOURCES.md
Labels: hacktoberfest-accepted

#298 added Leetcode/Rotate Image
  Leetcode/Rotate Image/readme.md
  Leetcode/Rotate Image/solution.cpp
Labels: hacktoberfest-accepted

#302 binary subbarrays with sum k leetcode solution
  Leetcode/Binary Subarrays With Sum/readme.md
  Leetcode/Binary Subarrays With Sum/solution.cpp
Labels: hacktoberfest-accepted

#310 Group Anagrams Leetcode
  Leetcode/Group Anagrams/readme.md
  Leetcode/Group Anagrams/solution.cpp
Labels: hacktoberfest-accepted

#314 420. Strong Password Checker
  Leetcode/Strong Password Checker/readme.md
  Leetcode/Strong Password Checker/solution.py
Labels: hacktoberfest-accepted

#315 Permutations Leetcode
  Leetcode/Permutations/readme.md
  Leetcode/Permutations/solution.cpp
  Leetcode/Subarray Sums Divisible by K/readme.md
  Leetcode/Subarray Sums Divisible by K/solution.cpp
Labels: hacktoberfest-accepted

#319 Range sum of BST added in Leetcode
  Leetcode/Range sum of BST/readme.md
  Leetcode/Range sum of BST/solution.py
Labels: hacktoberfest-accepted

#323 intersection
  Leetcode/Intersection of Two Arrays II/intersection_of_two_array.java
  Leetcode/Intersection of Two Arrays II/readme.md
Labels: hacktoberfest-accepted

#327 added Leetcode/Unique Paths II
  Leetcode/Unique Paths II/readme.md
  Leetcode/Unique Paths II/solution.cpp
Labels: hacktoberfest-accepted

#318 Added Leetcode Partition Array for Maximum Sum
  Leetcode/Delete Leaves with a given Value/readme.md
  Leetcode/Delete Leaves with a given Value/solution.cpp
  Leetcode/Partition array for Maximum Sum/readme.md
  Leetcode/Partition array for Maximum Sum/solution.cpp
Labels: hacktoberfest-accepted

#278 Added Messages Order in Hackerrank
  Hackerrank/Messages Order/readme.md
  Hackerrank/Messages Order/solution.cpp
Labels: hacktoberfest-accepted

#304 add Merge Sorted Array
  Leetcode/Merge Sorted Array/readme.md
  Leetcode/Merge Sorted Array/solution.cpp
Labels: hacktoberfest-accepted

#309 Leetcode Shuffle String
  Leetcode/Shuffle String/readme.md
  Leetcode/Shuffle String/solution.cpp
Labels: hacktoberfest-accepted

#330 Added Hackerrank Cycle Detection Solution
  Hackerrank/Cycle Detection/readme.md
  Hackerrank/Cycle Detection/solution.cpp
Labels: hacktoberfest-accepted

#312 Codeforces K Divisible Sum
  Codeforces/K Divisible Sum/readme.md
  Codeforces/K Divisible Sum/solution.cpp
Labels: hacktoberfest-accepted

#335 Added Leetcode Transform to Chessboard
  Leetcode/Transform to Chessboard/readme.md
  Leetcode/Transform to Chessboard/solution.java
Labels: hacktoberfest-accepted

#316 Added Solution For Hard Problem: Candy
  Leetcode/Candy/README.md
  Leetcode/Candy/Solution.cpp
Labels: hacktoberfest-accepted

#317 added Leetcode Regular Expression Matching
  Leetcode/Regular Expression Matching/readme.md
  Leetcode/Regular Expression Matching/solution.cpp
Labels: hacktoberfest-accepted

#320 Subarray Sums Divisible by K Leetcode
  Leetcode/Brick Wall/readme.md
  Leetcode/Brick Wall/solution.cpp
  Leetcode/Subarray Sums Divisible by K/readme.md
  Leetcode/Subarray Sums Divisible by K/solution.cpp
Labels: hacktoberfest-accepted

#325 Added a C solution to hackerrank problem
  Hackerrank/DigitFrequency/readme.md
  Hackerrank/DigitFrequency/solution.c
Labels: hacktoberfest-accepted

#334 Codechef solution make it divisible
  Codechef/Make it Divisible/readme.md
  Codechef/Make it Divisible/solution.cpp
Labels: hacktoberfest-accepted

#339 Added Hackerrank Solution for FIND THE RUNNING MEDIAN PROBLEM
  Hackerrank/Find the running median/readme.md
  Hackerrank/Find the running median/solution.cpp
Labels: hacktoberfest-accepted

#328 Maester map uri cpp
  URIOnlineJudge/Maesters Map/readme.md
  URIOnlineJudge/Maesters Map/solution.cpp
  URIOnlineJudge/The change/readme.md
  URIOnlineJudge/The change/solution.cpp
Labels: hacktoberfest-accepted

#341 Added Greedy Puppy Solution
  Codechef/Greedy Puppy/readme.md
  Codechef/Greedy Puppy/solution.cpp
Labels: hacktoberfest-accepted

#234 Added a very good cp guide alongwith practice problems.
  CP-DSA_RESOURCES.md
  Leetcode/Majority Element/readme.md
  Leetcode/Majority Element/solution.cpp
Labels: hacktoberfest-accepted

#321 added Leetcode/Unique Binary Search Trees
  Leetcode/Unqiue Binary Search Trees/readme.md
  Leetcode/Unqiue Binary Search Trees/solution.cpp
Labels: hacktoberfest-accepted

#345 Added Solution for Leetcode Nth Tribonacci Number
  Leetcode/Nth Tribonacci Number/readme.md
  Leetcode/Nth Tribonacci Number/solution.cpp
Labels: hacktoberfest-accepted

#349 Added -search in a rotated sorted array problem solution
  Leetcode/Search in rotated sorted array/readme.md
  Leetcode/Search in rotated sorted array/solution.cpp
Labels: hacktoberfest-accepted

#348 add easy cpp solution for same tree
  Leetcode/Same Tree/solution2.cpp
Labels: hacktoberfest-accepted

#350 Added a website
  CP-DSA_RESOURCES.md
Labels: hacktoberfest-accepted

#355 Alice bob faceoff
  Codechef/Alice and Bob faceoff/readme.md
  Codechef/Alice and Bob faceoff/solution.cpp
Labels: hacktoberfest-accepted

#342 Adding python code for Compare-the-triplets solution
  Hackerrank/compare-the-triplets/readme.md
  Hackerrank/compare-the-triplets/solution.py
Labels: hacktoberfest-accepted

#363 airplane seat problem added
  Leetcode/airplane seat assignment probablity/readme.md
  Leetcode/airplane seat assignment probablity/solution.cpp
Labels: hacktoberfest-accepted

#184 hit the lottery codeforces
  Codeforces/Hit Lottery/README.md
  Codeforces/Hit Lottery/hitthelottery.cpp
Labels: hacktoberfest-accepted

#197 Updated Leetcode and codechef folders by adding two new problems
  Codechef/Minimize the digit Sum/readme.md
  Codechef/Minimize the digit Sum/solution.cpp
Labels: hacktoberfest-accepted

#365 Added solution2.cpp with a better time complexity
  Hackerearth/Alice and candies/solution2.cpp
Labels: hacktoberfest-accepted

#198 added solution for A. CQXYM Count Permutations codeforces
  Codeforces/CQXYM Count Permutations/readme.md
  Codeforces/CQXYM Count Permutations/solution.cpp
Labels: hacktoberfest-accepted

#361 Leetcode Easy
  Leetcode/Find First and Last Position of Element in Sorted Array/README.md
  Leetcode/Find First and Last Position of Element in Sorted Array/Solution.cpp
Labels: hacktoberfest-accepted

#200 added Tricks solution from codeforces
  Codeforces/Tricks/readme.md
  Codeforces/Tricks/solution.cpp
Labels: hacktoberfest-accepted

#212 Solution in CPP
  Leetcode/Trapping rain water/solution2.cpp
Labels: hacktoberfest-accepted

#233 Added CodeChef Alternative Square Pattern Problem Code: SQALPAT
  Codechef/Alternative Square Pattern/README.md
  Codechef/Alternative Square Pattern/solution.cpp
Labels: hacktoberfest-accepted

#264 Added C++ Variadics in Hackerrank folder
  Hackerrank/CPP Variadics/readme.md
  Hackerrank/CPP Variadics/solution.cpp
Labels: hacktoberfest-accepted

#266 added java solution to Sort colors
  Leetcode/Sort colors/solution.java
Labels: hacktoberfest-accepted

#297 Non-decreasing arrays_DSA_Hackerearth
  Hackerearth/Non-decreasing arrays/READme.md
  Hackerearth/Non-decreasing arrays/Solution.cpp
  Hackerrank/Array Left Rotation/README.md
  Hackerrank/Array Left Rotation/Solution.cpp
Labels: hacktoberfest-accepted

#322 Check for BST
  GeeksForGeeks/Check for BST/readme.md
  GeeksForGeeks/Check for BST/solution.cpp
Labels: hacktoberfest-accepted

#336 Added Beautiful Triplets problem
  Hackerrank/Beautiful Triplets/README.md
  Hackerrank/Beautiful Triplets/solution.cpp
Labels: hacktoberfest-accepted

#369 alien dictionary added
  Leetcode/base 7/readme.md
  Leetcode/base 7/solution.cpp
  Leetcode/verify an alien dictionary/readme.md
  Leetcode/verify an alien dictionary/solution.cpp
Labels: hacktoberfest-accepted

#347 Added Codeforces Chess Tournament
  Codeforces/ChessTournament/readme.md
  Codeforces/ChessTournament/solution.cpp
Labels: hacktoberfest-accepted

#346 Added a website
  CP-DSA_RESOURCES.md
Labels: hacktoberfest-accepted

#362 Binary Tree Inorder Traversal Leetcode
  Leetcode/Binary Tree Inorder Traversal/readme.md
  Leetcode/Binary Tree Inorder Traversal/solution.cpp
Labels: hacktoberfest-accepted

#366 Update solution.cpp
  Hackerrank/Sales by Match/solution.cpp
Labels: hacktoberfest-accepted

#374 Solution of the longest palindromic subsequence is done
  Leetcode/LongestPalindromicSubsequence/readme.md
  Leetcode/LongestPalindromicSubsequence/solution.java
  Leetcode/Number of BSTs/readme.md
  Leetcode/Number of BSTs/solution.java
Labels: hacktoberfest-accepted

#378 Leetcode Remove Element
  Leetcode/Remove Element/readme.md
  Leetcode/Remove Element/solution.cpp
Labels: hacktoberfest-accepted

#368 ADDED HACKKERANK SWAP NODES ALGO SOLUTION
  Hackerrank/Swap Nodes/readme.md
  Hackerrank/Swap Nodes/solution.cpp
Labels: hacktoberfest-accepted

#372 Diameter of a Binary Tree!!
  Leetcode/Diameter Of The Binary Tree/Readme.md
  Leetcode/Diameter Of The Binary Tree/solution.cpp
Labels: hacktoberfest-accepted

#376 Leetcode The Skyline Problem
  Leetcode/The Skyline Problem/readme.md
  Leetcode/The Skyline Problem/solution.cpp
Labels: hacktoberfest-accepted

#380 Added Codechef Cars and Bikes
  Codechef/Cars and Bikes/Readme.md
  Codechef/Cars and Bikes/Solution.java
Labels: hacktoberfest-accepted

#384 Update CP-DSA_RESOURCES.md
  CP-DSA_RESOURCES.md
Labels: hacktoberfest-accepted

#388 Min cost to cut the stick leetcode question solved.
  Leetcode/Minimum Cost to cut stick/readme.md
  Leetcode/Minimum Cost to cut stick/solution.java
Labels: hacktoberfest-accepted

#396 Evaluate Reverse Polish Notation Leetcode
  Leetcode/Evaluate Reverse Polish Notation/readme.md
  Leetcode/Evaluate Reverse Polish Notation/solution.cpp
Labels: hacktoberfest-accepted

#400 added Leetcode Split Linked List in Parts
  Leetcode/Split Linked List in Parts/readme.md
  Leetcode/Split Linked List in Parts/solution.cpp
Labels: hacktoberfest-accepted
